#include "../inc/Server.hpp"

void	Server::_genMeme(Chan* chan)
{
	std::vector<std::string>			meme;
	std::string					str = "";

	this->_memes.clear();
	meme.clear();
	str = ":BOT PRIVMSG " + chan->getName() + "       ⠀⠀⢀⣠⠤⠶⠖⠒⠒⠶⠦⠤⣄⠀⠀⠀⣀⡤⠤⠤⠤⠤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "       ⠀⣴⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⣦⠞⠁⠀⠀⠀⠀⠀⠀⠉⠳⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "       ⡾⠁⠀⠀⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⣘⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + " ⠀      ⠀⠀⠀⢀⡴⠚⠉⠁⠀⠀⠀⠀⠈⠉⠙⠲⣄⣤⠤⠶⠒⠒⠲⠦⢤⣜⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⡄⠀⠀⠀⠀⠀⠀⠀⠉⠳⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀   ⠀⠀⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⠹⣆⠀⠀⠀⠀⠀⠀⣀⣀⣀⣹⣄⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀   ⠀⠀⠀⣠⠞⣉⣡⠤⠴⠿⠗⠳⠶⣬⣙⠓⢦⡈⠙⢿⡀⠀⠀⢀⣼⣿⣿⣿⣿⣿⡿⣷⣤⡀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⠀⠀⣾⣡⠞⣁⣀⣀⣀⣠⣤⣤⣤⣄⣭⣷⣦⣽⣦⡀⢻⡄⠰⢟⣥⣾⣿⣏⣉⡙⠓⢦⣻⠃⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⠀⠀⠉⠉⠙⠻⢤⣄⣼⣿⣽⣿⠟⠻⣿⠄⠀⠀⢻⡝⢿⡇⣠⣿⣿⣻⣿⠿⣿⡉⠓⠮⣿⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀   ⠀⠀⠀⠙⢦⡈⠛⠿⣾⣿⣶⣾⡿⠀⠀⠀⢀⣳⣘⢻⣇⣿⣿⣽⣿⣶⣾⠃⣀⡴⣿⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀   ⠀⠀⠀⠀⠀⠙⠲⠤⢄⣈⣉⣙⣓⣒⣒⣚⣉⣥⠟⠀⢯⣉⡉⠉⠉⠛⢉⣉⣡⡾⠁⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⠀⣠⣤⡤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢈⡿⠋⠀⠀⠀⠀⠈⠻⣍⠉⠀⠺⠿⠋⠙⣦⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⣀⣥⣤⠴⠆⠀⠀⠀⠀⠀⠀⠀⣀⣠⠤⠖⠋⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⠀⠀⠀⠀⠀⢸⣧⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠸⢫⡟⠙⣛⠲⠤⣄⣀⣀⠀⠈⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠏⣨⠇⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "      ⠀⠀⠻⢦⣈⠓⠶⠤⣄⣉⠉⠉⠛⠒⠲⠦⠤⠤⣤⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⠴⢋⡴⠋⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀   ⠀⠀⠉⠓⠦⣄⡀⠈⠙⠓⠒⠶⠶⠶⠶⠤⣤⣀⣀⣀⣀⣀⣉⣉⣉⣉⣉⣀⣠⠴⠋⣿⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀   ⠀⠀⠀⠀⠉⠓⠦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⠁⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠉⠉⠙⠛⠒⠒⠒⠒⠒⠤⠤⠤⠒⠒⠒⠒⠒⠒⠚⢉⡇⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠴⠚⠛⠳⣤⠞⠁⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⠚⠁⠀⠀⠀⠀⠘⠲⣄⡀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⣴⠋⠙⢷⡋⢙⡇⢀⡴⢒⡿⢶⣄⡴⠀⠙⠳⣄⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠙⢦⡀⠈⠛⢻⠛⢉⡴⣋⡴⠟⠁⠀⠀⠀⠀⠈⢧⡀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠀⢻⡄⠀⠘⣶⢋⡞⠁⠀⠀⢀⡴⠂⠀⠀⠀⠀⠹⣄⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠈⠻⢦⡀⠀⣰⠏⠀⠀⢀⡴⠃⢀⡄⠙⣆ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠀⠀⢠⡾⢷⡄⠀⠀⠀⠀⠉⠙⠯⠀⠀⡴⠋⠀⢠⠟⠀⠀⢹ \r\n";
	meme.push_back(str);
	this->_memes.insert(std::make_pair(0, meme));

	meme.clear();
	str.clear();
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡶⠟⠛⠉⠙⠻⢿⣤⡀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⣀⣤⣶⠿⠯⠤⠄⠀⠀⠀⠀⠀⠙⢿⣄⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣛⣻⢯⣅⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠴⠞⠋⠉⠀⠉⠛⠿⡦⡀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⠭⣍⣉⠛⢾⣝⡂⠀⠀⠀⠀⣠⡴⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⡆⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣇⠀⣰⣿⣿⣿⣿⡙⢂⣠⠴⠿⠥⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⡄⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣿⣏⠳⢿⣿⣿⣿⢛⡇⠋⠡⢒⣒⣒⣒⣛⡛⠦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠘⡷⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⣿⠁⠘⠈⠀⠀⣈⡙⠳⠞⣠⡴⠊⠉⢉⣽⣦⣌⠉⠓⠦⣍⠳⡄⠀⠀⠀⠀⠀⠀⢹⠃ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⡇⠀⠀⠀⠀⡤⠞⠛⠓⠀⢧⣙⠲⢤⣾⣿⣽⣿⣿⡷⢤⡈⢧⠹⡄⠀⠀⠀⠀⠀⠀⡇ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⣀⣴⠾⠻⢶⣄⠀⠀⠀⠀⢰⣿⣇⠹⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⠓⢦⣌⠙⠛⠛⠛⠓⠒⠛⠒⠷⠇⠀⠀⠀⠀⠀⠀⣿ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⡶⠶⠒⠛⣫⣥⡴⠒⠂⢻⣧⠀⠀⠀⣸⣇⠈⢷⡈⠓⠦⣄⡀⠀⠀⠀⠀⠀⠈⣧⠀⠈⠉⠓⠒⠒⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⣿⡇⠀⠀⠀⠀⢀⣇⠠⠤⣾⠻⠿⠶⠶⣿⠛⢦⡀⠉⠳⣄⡀⠉⠙⠲⠤⣄⣀⡀⠈⠓⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⡿⠛⠶⠶⠒⠚⠛⠙⢦⣼⠃⠀⠀⠀⠀⢿⠀⠈⠙⠦⣄⠀⠙⠓⢦⣄⣀⠀⠈⠉⠓⠲⠦⠤⠤⣤⣀⣠⣄⠃⠀⠀⠀⠀⠀⠀⠀⠀⢀⠇ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⣿⣄⢀⣀⣠⡤⠤⠤⢾⡏⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠈⠙⠲⠦⣤⣀⣈⠉⠛⠒⠶⠦⠤⠤⠤⣤⠄⠉⣻⠆⠀⠀⠀⠀⠀⠀⠀⠀⠸⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⣽⡿⠉⠁⠀⠀⠀⢀⣼⠁⠀⠀⠀⠀⠀⠀⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠛⠓⠒⠒⠒⠒⠒⠒⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⣇⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠙⣷⣀⣀⣤⠴⠒⠋⢹⣧⣄⣀⣀⣀⣀⣀⣹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡏⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠸⣿⡁⠀⠀⣀⣴⠟⠉⠉⠉⠉⠉⠉⠛⢻⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⠃⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠙⠛⠛⠛⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠏⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡏⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡿⠁⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣸⣧⡀⣀⣀⣀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠒⠒⠉⠉⠉⠁⠀⠀⠉⠉⠉⠉⠉ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	this->_memes.insert(std::make_pair(1, meme));

	meme.clear();
	str.clear();
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⡠⠖⠋⠉⠙⠓⠦⣄⣀⠴⠒⢉⣉⣉⠉⠙⠲⣄⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⡜⠀⠀⠀⠀⠀⠀⠀⣼⣵⣒⠭⠭⠤⠤⣝⡆⠀⠈⠳⡄⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⣀⠴⣾⡟⠉⠉⢍⠀⠀⢉⣿⣿⠿⠗⠐⠒⠒⠠⣄⡉⠆⠀⠀⠘⣄⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⡾⠁⠠⠤⠬⠷⢦⣌⣃⣰⠟⠉⠀⠀⢀⡀⡀⠀⠀⠀⠉⠳⡄⠀⠀⢸⡦⡀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠉⠉⠉⠉⠁⢿⣿⣽⡟⡟⠉⠉⠉⠉⠹⣿⣿⣿⠛⣗⣲⣶⡧⠖⠂⠀⠇⠈⢂⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⣶⣒⡒⠒⠶⠤⠿⢯⣦⣿⣶⠖⠲⠶⠶⠾⠿⢛⣋⣡⠎⠀⠀⠀⠀⠀⠀⠀⠀⢂ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠁⠙⢯⣄⡀⠀⠀⢀⣼⠁⠉⠳⢖⡒⠒⠒⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⣴⡞⠁⠉⠉⠛⠉⠀⠀⠀⠀⠀⠈⠙⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠻⡟⢦⣄⣀⣀⣀⣀⣀⣀⣀⣠⢤⢤⣴⣶⣶⣶⣶⣶⣶⡆⠀⠀⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠻⣃⣛⣛⣿⣿⣿⣻⣿⣿⡶⠾⠿⣿⠿⠛⠉⣹⠋⠉⠀⠀⡄⠀⠀⠀⠀⠀⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠈⠙⡷⣼⡟⠀⠳⡀⠀⢀⠴⠊⡁⠀⣠⠞⠁⠀⠀⠒⠋⠁⠀⠀⠀⢀⣠⣴ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "         ⠀⠀⠀⠀⠀⠉⢷⠂⠀⠙⠚⠁⠀⢀⣴⣞⡀⢀⣀⢀⣀⡀⣤⣤⣔⣒⡽⠟⠋⠀ \r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⢸⣆⠀⠀⠀⠀⠀⠈⢀⡼⠷⣿⠛⠛⠛⠛⠉⠉⠉⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⣠⠋⠙⢦⣀⠀⠀⠀⠀⠀⠀⢤⣿⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⡀\r\n";
	meme.push_back(str);
	this->_memes.insert(std::make_pair(2, meme));


	meme.clear();
	str.clear();
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡴⢶⡖⠒⠂⠒⠒⠶⢦⣀⠀⠀⠀⠀⠀⠀⣠⣤⠴⠤⠶⢤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣴⡿⠙⠋⠉⠀⠀⠀⠀⠀⠈⠀⠪⣵⣤⣤⠖⡺⠿⠋⠀⠀⠀⠀⠀⠺⣝⠲⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⡝⣦⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⣴⣯⠟⠁⠀⠀⠀⠀⠀⡀⠄⠀⠀⠀⠀⠢⠤⣤⡀⠘⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⠹⣠⡀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⣰⣻⠏⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠓⢾⡦⠐⠂⠀⠀⠀⠀⠀⠀⠐⠂⠀⠆⢻⣛⠦⡀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⢀⣰⢿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡤⠤⠄⠀⠐⠲⠀⠹⢦⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠑⢼⠷⣄⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⢠⣴⣿⢧⡞⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡴⢞⡯⠕⠒⠂⠉⠁⠀⠀⠒⠒⠢⢿⣷⣶⡮⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠑⢾⠳⡄\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⢰⣟⠞⠁⠘⠁⠀⠀⠀⠀⠀⢀⣀⠚⠋⠁⠚⠋⢁⣀⣠⣤⣤⣤⣤⣤⣤⣀⣀⠀⠈⠙⠀⠀⢀⣠⣤⣤⡤⠤⠤⠤⣤⠀⠤⢬⣦⢳\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⣴⠿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣆⠰⢀⣤⠶⠛⠋⠉⠉⣠⣤⣤⣼⣷⣤⣬⣽⠷⠂⠀⠛⠛⠛⠓⠒⠒⠲⠒⠒⠚⠛⠛⢣⡀⠈⣿\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⣼⣷⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⡃⠀⠠⠐⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⠀⢠⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡽⣳⣿\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠋⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢳⡶⣤⣀⠀⠀⠀⠀⠀⠀⢀⣀⣤⡴⠛⠉⠀⠀⠀⠀⠀⠀⢀⠠⠄⠂⠀⣰⢾⣿⠙⠒\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢆⡀⠀⠀⠀⠀⠾⠛⠁⣾⡟⠀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣮⣿⡛⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠴⠞⠉⠐⠋⠁⠀⠀⠀⠉⠙⠯⢲⠖⠂⠉⠉⠉⠙⣮⢿⣿⣧⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣤⣾⠤⠤⠤⠤⡶⠶⣶⣶⣶⣖⣒⣒⣛⠛⡛⣛⣲⣶⣶⣦⣬⠿⣼⣻⣦⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⠀⠀⣾⠛⣩⣵⠿⣶⠶⠿⢾⠛⠛⢻⡟⠛⠻⣏⠙⠻⣿⡟⠛⡻⣿⠉⠙⣿⢿⠀⠀⣿⢾⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣆⠀⣿⡀⢻⡄⠀⢸⡆⠀⠸⡆⣤⣘⣷⣆⣀⣿⣀⣀⣁⣿⣒⣁⣸⡄⠀⣿⠞⠀⣠⣿⡾⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣆⡙⢷⣄⡙⢦⣼⣿⠃⠀⣿⡟⠁⢿⡍⠉⠉⡏⠉⠉⣾⠁⠉⢹⢇⣴⠃⠀⣤⣯⡿⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⣦⠉⠻⣦⡉⠙⣦⣤⡟⠀⠀⢸⠀⠀⣼⠃⠀⢀⣟⣀⣴⣿⠟⢁⣠⣾⣷⠟⠁⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢳⣄⠀⠀⠀⠀⠀⠈⠙⠆⠀⠉⠻⠷⢯⣭⣭⣭⣼⣿⣯⣽⣶⣿⣿⣿⣿⣿⠿⢛⣿⢿⡿⠋⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⣻⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣟⡿⠋⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⠋⠙⠿⣯⣟⣶⣤⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣠⣶⣯⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⡇⠀⠀⠀⠙⠻⠷⢦⣌⣉⣉⠙⠓⠒⠶⠦⠤⠤⠤⠀⠀⠀⠀⠀⢀⢀⣀⣀⣀⣀⢠⣤⣤⣞⣻⣿⡿⠏⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠛⠿⠷⠶⠶⠶⠤⠤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⠶⠟⠛⠉⠛⢷⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	str = ":BOT PRIVMSG " + chan->getName() + "          ⡇⠀⠀⠀⢀⣀⣀⠀⠀⠀⠀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⢀⡀⠀⠀⣀⠀⠀⠀⠀⠙⠳⣼⠳⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\r\n";
	meme.push_back(str);
	this->_memes.insert(std::make_pair(3, meme));
}
