#ifndef RPL_HPP
#define RPL_HPP

#define RPL_WELCOME_001(fullId) (":Welcome in our awesome chat " + fullId + "!")
#define RPL_YOURHOST_002(serverName, version) (":Your host is " + serverName + ", running version " + version)
#define RPL_CREATED_003(dateTime) (":This server was created " + dateTime)
#define RPL_MYINFO_004(info) (info)
#define RPL_ISUPPORT_005(info) (info + " :are supported by this server")

#define RPL_UMODEIS_221 (":+")

#define RPL_LISTSTART_321 ("Channel :Users Name")
#define RPL_LIST_322(chanName, nbChanUsers, topic) (chanName + " " + nbChanUsers + " " + topic)
#define RPL_LISTEND_323 (":End of /LIST")
#define RPL_CHANNELMODEIS_324(chanName, modesAndParams) (chanName + " " + modesAndParams)
#define RPL_NOTOPIC_331(chanName) (chanName + " :No topic is set")
#define RPL_TOPIC_332(chanName, topic) (chanName + " :" + topic)
#define RPL_NAMREPLY_353(chanName, clientsNamesInChan) ("= " + chanName + " :" + clientsNamesInChan)
#define RPL_ENDOFNAMES_366(chanName) (chanName + " :End of /NAMES list")
#define RPL_ENDOFBANLIST_368(chanName) (chanName + " :End of channel ban list")
#define RPL_MOTD_372(motd) (":- " + motd)
#define RPL_MOTDSTART_375(serverName) (":- " + serverName + " message of the day -")
#define RPL_ENDOFMOTD_376 (":End of message of the day")

#define ERR_NOSUCHNICK_401(nick) (nick + " :No such nick/channel")
#define ERR_NOSUCHSERVER_402(serverName) (serverName + " :No such server")
#define ERR_NOSUCHCHANNEL_403(chanName) (chanName + " :No such channel")
#define ERR_CANNOTSENDTOCHAN_404(chanName) (chanName + " :Cannot send to channel")
#define ERR_NORECIPIENT_411 (":No recipient given")
#define ERR_UNKNOWNCOMMAND_421(cmd) (cmd + " :Unknown command")
#define ERR_NOMOTD_422 (":Message of the day file is missing")
#define ERR_NONICKNAMEGIVEN_431 (":No nickname given")
#define ERR_ERRONEUSNICKNAME_432(nick) (nick + " :Erroneous nickname")
#define ERR_NICKNAMEINUSE_433(nick) (nick + " :Nickname is already in use")
#define ERR_USERNOTINCHANNEL_441(nick, chanName) (nick + " " + chanName + " :They aren't on that channel")
#define	ERR_NOTONCHANNEL_442(chanName) (chanName + " :You're not on that channel")
#define ERR_USERONCHANNEL_443(nick, chanName) (nick + " " + chanName + " :is already on channel")
#define ERR_NOTREGISTERED_451 (":You have not registered")
#define ERR_NEEDMOREPARAMS_461(cmd) (cmd + " :Not enough parameters")
#define ERR_ALREADYREGISTRED_462 (":Unauthorized command (already registered)")
#define ERR_PASSWDMISMATCH_464 (":Password incorrect")
#define ERR_CHANNELISFULL_471(chanName) (chanName + " :Cannot join channel (+l)")
#define ERR_UNKNOWNMODE_472(charMode, chanName) (charMode + " :is unknown mode char to me for " + chanName)
#define ERR_INVITEONLYCHAN_473(chanName) (chanName + " :Cannot join channel (+i)")
#define	ERR_CHANOPRIVSNEEDED_482(chanName) (chanName + " :You're not channel operator")

#define ERR_UMODEUNKNOWNFLAG_501 (":Unknown MODE flag")
#define ERR_USERSDONTMATCH_502(action) (":Cannot " + action + " for other users")
#endif
